name: Build and Push App Container

on:
  push:
    branches: [main]
    paths:
      - 'app/**'
      - 'app/Dockerfile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # Azure Login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Login to Azure Container Registry
      - name: ACR Login
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      # Build & Push Docker Image
      - name: Build and Push Image to ACR
        uses: docker/build-push-action@v3
        with:
          context: ./app
          push: true
          tags: |
            ${{ secrets.ACR_LOGIN_SERVER }}/hello-world:${{ github.sha }}
            ${{ secrets.ACR_LOGIN_SERVER }}/hello-world:latest